'use strict';

const STORE_KEY='sala_giochi_locale_v1';
const app=document.getElementById('app');
const backBtn=document.getElementById('backBtn');
const homeBtn=document.getElementById('homeBtn');
const titleEl=document.getElementById('pageTitle');
const subEl=document.getElementById('pageSub');
const dialog=document.getElementById('difficultyDialog');
const difficultyTitle=document.getElementById('difficultyTitle');
const toastEl=document.getElementById('toast');
let pendingGame=null, activeTimer=null, activeStart=0, activeSaved=false;

const GAME_NAMES={mixed:'Partita Mista',sudoku:'Sudoku',wordsearch:'Cerca-parole',anagram:'Anagrammi',quiz:'Quiz',logic:'Logica',escape:'Escape Room'};
const LEVEL_NAMES={easy:'Facile',medium:'Medio',hard:'Difficile',extreme:'Difficilissimo'};
const ICONS={mixed:'🎲',sudoku:'🔢',wordsearch:'🔤',anagram:'🔡',quiz:'❓',logic:'🧠',escape:'🔐'};

const freshStore=()=>({version:1,createdAt:new Date().toISOString(),history:[],stats:{}});
function loadStore(){try{return {...freshStore(),...JSON.parse(localStorage.getItem(STORE_KEY)||'{}')}}catch{return freshStore()}}
let store=loadStore();
function persist(){localStorage.setItem(STORE_KEY,JSON.stringify(store))}
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function norm(s){return String(s).trim().toLocaleUpperCase('it').normalize('NFD').replace(/[\u0300-\u036f]/g,'')}
function shuffle(a,r=Math.random){const x=[...a];for(let i=x.length-1;i>0;i--){const j=Math.floor(r()*(i+1));[x[i],x[j]]=[x[j],x[i]]}return x}
function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),1800)}
function fmtTime(sec){const m=Math.floor(sec/60),s=sec%60;return `${m}:${String(s).padStart(2,'0')}`}
function startTimer(){stopTimer();activeStart=Date.now();const el=document.getElementById('timer');if(!el)return;const tick=()=>el.textContent=fmtTime(Math.floor((Date.now()-activeStart)/1000));tick();activeTimer=setInterval(tick,1000)}
function stopTimer(){if(activeTimer){clearInterval(activeTimer);activeTimer=null}return activeStart?Math.floor((Date.now()-activeStart)/1000):0}
function setHeader(title,sub=''){titleEl.textContent=title;subEl.textContent=sub;backBtn.classList.toggle('hidden',title==='Sala Giochi');homeBtn.classList.toggle('hidden',title==='Sala Giochi')}
function endRecord(game,level,score,success,extra={}){if(activeSaved)return;activeSaved=true;const seconds=stopTimer();const row={id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),date:new Date().toISOString(),game,level,score:Math.round(score),success,seconds,...extra};store.history.unshift(row);store.history=store.history.slice(0,250);const k=`${game}:${level}`;const s=store.stats[k]||{played:0,won:0,bestScore:0,bestTime:null};s.played++;if(success)s.won++;s.bestScore=Math.max(s.bestScore,row.score);if(success&&(s.bestTime===null||seconds<s.bestTime))s.bestTime=seconds;store.stats[k]=s;persist();return row}

backBtn.onclick=()=>{stopTimer();renderHome()}; homeBtn.onclick=()=>{stopTimer();renderHome()};
dialog.addEventListener('close',()=>{const level=dialog.returnValue;if(level&&level!=='cancel'&&pendingGame)startGame(pendingGame,level)});

function renderHome(){activeSaved=false;setHeader('Sala Giochi','Un solo giocatore · archivio locale · v1.2.0');const total=store.history.length,wins=store.history.filter(x=>x.success).length,best=store.history.reduce((m,x)=>Math.max(m,x.score||0),0);app.innerHTML=`
<section class="hero"><div class="hero-kicker">🎮 SALA GIOCHI</div><h2>Cosa vuoi giocare?</h2><p>Scegli una sfida, imposta il livello e gioca. Tutto resta memorizzato soltanto su questo dispositivo.</p><div class="hero-note"><span>● 4 livelli</span><span>◉ Offline</span><span>▣ Archivio locale</span></div></section>
<button class="daily-card" onclick="renderDaily()"><span class="daily-icon">⭐</span><span><strong>Sfida del giorno</strong><small>Una nuova prova da affrontare ogni giorno</small></span><span class="card-arrow">›</span></button>
<div class="section-title"><h3>Scegli un gioco</h3><small>Facile · Medio · Difficile · Difficilissimo</small></div>
<div class="grid">
${gameCard('mixed','Partita Mista','Sei prove diverse in una sola partita')}
${gameCard('sudoku','Sudoku','Griglia 9×9 con soluzione unica')}
${gameCard('wordsearch','Cerca-parole','Trova le parole nascoste')}
${gameCard('anagram','Anagrammi','Ricomponi le parole')}
${gameCard('quiz','Quiz','Cultura generale e curiosità')}
${gameCard('logic','Logica','Sequenze, deduzioni e codici')}
${gameCard('escape','Escape Room','Enigmi concatenati in una storia')}
</div>
<div class="section-title"><h3>Le tue statistiche</h3><button class="secondary" onclick="renderArchive()">Apri archivio</button></div>
<div class="stat-grid"><div class="stat"><b>${total}</b><span>Partite</span></div><div class="stat"><b>${wins}</b><span>Completate</span></div><div class="stat"><b>${total?Math.round(wins/total*100):0}%</b><span>Successo</span></div><div class="stat"><b>${best}</b><span>Record punti</span></div></div>
<p class="footer-note">🔒 Nessun dato viene inviato a un server. Il browser conserva lo storico in memoria locale; dall'Archivio puoi esportare un backup JSON.</p>`}
function gameCard(id,name,desc){return `<button class="game-card game-${id}" onclick="chooseDifficulty('${id}')"><span class="game-icon">${ICONS[id]}</span><strong>${name}</strong><small>${desc}</small><span class="mini-arrow">›</span></button>`}
function chooseDifficulty(game){pendingGame=game;difficultyTitle.textContent=`${ICONS[game]} ${GAME_NAMES[game]} · livello`;dialog.showModal()}
function gameShell(game,level,body){return `<section class="game-shell game-${game}"><div class="game-head"><span class="badge">${ICONS[game]} ${GAME_NAMES[game]} · ${LEVEL_NAMES[level]}</span><span id="timer" class="timer">0:00</span></div>${body}</section>`}
function startGame(game,level){activeSaved=false;setHeader(GAME_NAMES[game],LEVEL_NAMES[level]);({sudoku:startSudoku,wordsearch:startWordSearch,anagram:startAnagram,quiz:startQuiz,logic:startLogic,escape:startEscape,mixed:startMixed}[game])(level)}

// ---------- Sudoku ----------
function pattern(r,c){return (r*3+Math.floor(r/3)+c)%9}
function sudokuFull(){const rows=shuffle([0,1,2]).flatMap(g=>shuffle([0,1,2]).map(r=>g*3+r));const cols=shuffle([0,1,2]).flatMap(g=>shuffle([0,1,2]).map(c=>g*3+c));const nums=shuffle([1,2,3,4,5,6,7,8,9]);return rows.flatMap(r=>cols.map(c=>nums[pattern(r,c)]))}
function countSolutions(board,limit=2){let count=0;function go(){if(count>=limit)return;let idx=-1,best=null;for(let i=0;i<81;i++){if(board[i])continue;const cand=[];for(let n=1;n<=9;n++)if(validSudoku(board,i,n))cand.push(n);if(!cand.length)return;if(!best||cand.length<best.length){best=cand;idx=i;if(cand.length===1)break}}if(idx<0){count++;return}for(const n of best){board[idx]=n;go();board[idx]=0;if(count>=limit)return}}go();return count}
function validSudoku(b,i,n){const r=Math.floor(i/9),c=i%9;for(let k=0;k<9;k++){if(b[r*9+k]===n||b[k*9+c]===n)return false}const br=Math.floor(r/3)*3,bc=Math.floor(c/3)*3;for(let rr=br;rr<br+3;rr++)for(let cc=bc;cc<bc+3;cc++)if(b[rr*9+cc]===n)return false;return true}
function makeSudoku(level){const solution=sudokuFull(),puzzle=[...solution];const target={easy:40,medium:33,hard:28,extreme:24}[level];let clues=81;for(const idx of shuffle([...Array(81).keys()])){if(clues<=target)break;const old=puzzle[idx];puzzle[idx]=0;if(countSolutions([...puzzle],2)!==1)puzzle[idx]=old;else clues--}return {solution,puzzle}}
function startSudoku(level){const g=makeSudoku(level);let hints={easy:3,medium:2,hard:1,extreme:1}[level];app.innerHTML=gameShell('sudoku',level,`<div class="message">Completa la griglia. Lo schema generato ha una sola soluzione.</div><div id="sudoku" class="sudoku"></div><div class="actions"><button class="secondary" id="checkSudoku">Controlla</button><button class="secondary" id="hintSudoku">💡 Suggerimento (${hints})</button><button class="primary" id="finishSudoku">Concludi</button></div><div id="sudokuMsg"></div>`);const grid=document.getElementById('sudoku');g.puzzle.forEach((v,i)=>{const inp=document.createElement('input');inp.inputMode='numeric';inp.maxLength=1;inp.dataset.i=i;if(v){inp.value=v;inp.readOnly=true;inp.className='given'}else inp.addEventListener('input',()=>{inp.value=inp.value.replace(/[^1-9]/g,'').slice(0,1);if([...grid.querySelectorAll('input')].every((x,j)=>Number(x.value)===g.solution[j]))finish(true)});grid.appendChild(inp)});const msg=document.getElementById('sudokuMsg');document.getElementById('checkSudoku').onclick=()=>{let wrong=0;grid.querySelectorAll('input:not(.given)').forEach(x=>{const i=+x.dataset.i;x.style.background=(x.value&&+x.value!==g.solution[i])?'#fef2f2':'';if(x.value&&+x.value!==g.solution[i])wrong++});msg.innerHTML=`<div class="message ${wrong?'bad':'ok'}">${wrong?`Ci sono ${wrong} valori errati.`:'Nessun errore tra i valori inseriti.'}</div>`};document.getElementById('hintSudoku').onclick=()=>{if(!hints)return toast('Nessun suggerimento rimasto');const empty=[...grid.querySelectorAll('input:not(.given)')].filter(x=>Number(x.value)!==g.solution[+x.dataset.i]);if(!empty.length)return;const x=empty[Math.floor(Math.random()*empty.length)];x.value=g.solution[+x.dataset.i];x.style.background='#fff7d6';hints--;document.getElementById('hintSudoku').textContent=`💡 Suggerimento (${hints})`};document.getElementById('finishSudoku').onclick=()=>{const ok=[...grid.querySelectorAll('input')].every((x,j)=>Number(x.value)===g.solution[j]);finish(ok)};startTimer();function finish(ok){const sec=Math.floor((Date.now()-activeStart)/1000),filled=[...grid.querySelectorAll('input')].filter(x=>x.value).length;const score=ok?Math.max(100,1000-sec-Math.max(0,81-filled)*2):Math.round(filled/81*500);endRecord('sudoku',level,score,ok);msg.innerHTML=`<div class="message ${ok?'ok':'bad'}">${ok?'Sudoku completato!':'Partita registrata come non completata.'} Punteggio: <b>${score}</b>.</div>`}}

// ---------- Cerca-parole ----------
const WORD_THEMES={
  'Animali':['TIGRE','DELFINO','CAVALLO','PANDA','VOLPE','AQUILA','GIRAFFA','ZEBRA','LONTRA','FALCO','KOALA','ORSO','LUPO','CIGNO','RICCIO','TASSO','FOCA','GATTO'],
  'Cucina':['PASTA','RISOTTO','FORNO','TEGAME','COLTELLO','FARINA','LIEVITO','PENTOLA','MESTOLO','CANNELLA','RAGU','BRODO','TORTA','PANE','OLIO','SALE','PEPE','CREMA'],
  'Geografia':['ITALIA','EUROPA','TORINO','ROMA','ALPI','FIUME','ISOLA','OCEANO','DESERTO','PIANURA','COLLINA','VULCANO','LAGO','COSTA','VALLE','PORTO','NORD','SUD']
};
function startWordSearch(level){const size={easy:10,medium:12,hard:15,extreme:17}[level],count={easy:8,medium:12,hard:15,extreme:18}[level];const theme=shuffle(Object.keys(WORD_THEMES))[0];let words=shuffle(WORD_THEMES[theme].filter(w=>w.length<=size)).slice(0,count);const dirs=level==='easy'?[[1,0],[0,1]]:level==='medium'?[[1,0],[0,1],[1,1],[-1,1],[-1,0],[0,-1]]:[[1,0],[0,1],[1,1],[-1,1],[-1,0],[0,-1],[-1,-1],[1,-1]];const grid=Array(size*size).fill('');const placed=[];for(const w of words){let ok=false;for(let tries=0;tries<300&&!ok;tries++){const [dx,dy]=dirs[Math.floor(Math.random()*dirs.length)],x=Math.floor(Math.random()*size),y=Math.floor(Math.random()*size);const endx=x+dx*(w.length-1),endy=y+dy*(w.length-1);if(endx<0||endx>=size||endy<0||endy>=size)continue;let good=true,cells=[];for(let i=0;i<w.length;i++){const xx=x+dx*i,yy=y+dy*i,idx=yy*size+xx;cells.push(idx);if(grid[idx]&&grid[idx]!==w[i]){good=false;break}}if(good){cells.forEach((idx,i)=>grid[idx]=w[i]);placed.push({word:w,cells});ok=true}}}words=placed.map(p=>p.word);const letters='ABCDEFGHIJKLMNOPQRSTUVWXYZ';for(let i=0;i<grid.length;i++)if(!grid[i])grid[i]=letters[Math.floor(Math.random()*letters.length)];let first=null,found=new Set();app.innerHTML=gameShell('wordsearch',level,`<div class="message">Tema: <b>${theme}</b>. Tocca la prima e poi l'ultima lettera di una parola.</div><div id="wordGrid" class="word-grid" style="grid-template-columns:repeat(${size},1fr)"></div><div id="wordList" class="word-list"></div><div id="wordMsg"></div>`);const wg=document.getElementById('wordGrid');grid.forEach((l,i)=>{const b=document.createElement('button');b.className='letter';b.textContent=l;b.dataset.i=i;b.onclick=()=>select(i);wg.appendChild(b)});renderWords();startTimer();function renderWords(){document.getElementById('wordList').innerHTML=words.map(w=>`<span class="word-chip ${found.has(w)?'done':''}">${w}</span>`).join('')};function select(i){if(first===null){first=i;wg.children[i].classList.add('selected');return}const path=linePath(first,i,size);wg.children[first].classList.remove('selected');first=null;if(!path)return toast('Seleziona una linea orizzontale, verticale o diagonale');const text=path.map(j=>grid[j]).join('');const rev=[...text].reverse().join('');const p=placed.find(p=>!found.has(p.word)&&(p.word===text||p.word===rev)&&sameCells(p.cells,path));if(p){found.add(p.word);path.forEach(j=>wg.children[j].classList.add('found'));renderWords();if(found.size===words.length){const sec=Math.floor((Date.now()-activeStart)/1000),score=Math.max(100,800-sec);endRecord('wordsearch',level,score,true);document.getElementById('wordMsg').innerHTML=`<div class="message ok">Tutte le parole trovate. Punteggio: <b>${score}</b>.</div>`}}else toast('Non è una delle parole da trovare')}}
function linePath(a,b,size){const ax=a%size,ay=Math.floor(a/size),bx=b%size,by=Math.floor(b/size),dx=Math.sign(bx-ax),dy=Math.sign(by-ay),sx=Math.abs(bx-ax),sy=Math.abs(by-ay);if(!(sx===0||sy===0||sx===sy))return null;const len=Math.max(sx,sy)+1,out=[];for(let i=0;i<len;i++)out.push((ay+dy*i)*size+(ax+dx*i));return out}
function sameCells(a,b){return a.length===b.length&&a.every(x=>b.includes(x))}

// ---------- Anagrammi ----------
const ANAGRAMS={easy:[['TEATRO','Spettacolo'],['CAMERA','Casa'],['GELATO','Cibo'],['FIUME','Geografia'],['PESCA','Natura'],['TRENO','Trasporti'],['LIBRO','Cultura'],['PIANO','Musica'],['BOSCO','Natura'],['PORTA','Casa'],['TORRE','Architettura'],['PIANTA','Natura']],medium:[['ASTRONAUTA','Spazio'],['PIRAMIDE','Storia'],['BIBLIOTECA','Cultura'],['SCULTURA','Arte'],['ORCHESTRA','Musica'],['VULCANO','Geografia'],['PANORAMA','Paesaggio'],['GIRASOLE','Natura'],['LABIRINTO','Enigma'],['CANGURO','Animali'],['TELESCOPIO','Scienza'],['CASTELLO','Storia']],hard:[['ARCHEOLOGIA','Scienza umana'],['COSTELLAZIONE','Astronomia'],['BIODIVERSITA','Natura'],['CARTOGRAFIA','Geografia'],['METAMORFOSI','Trasformazione'],['CRITTOGRAFIA','Codici'],['ELETTROMAGNETE','Fisica'],['PARALLELEPIPEDO','Geometria'],['INTERPRETAZIONE','Comprensione'],['SPETTROSCOPIA','Scienza'],['MICROSCOPIO','Laboratorio'],['PROBABILITA','Matematica']],extreme:[['INCOMPRENSIBILITA','Linguaggio'],['ANTROPOLOGICHE','Scienze sociali'],['INTERDISCIPLINARE','Conoscenza'],['ELETTROENCEFALOGRAMMA','Medicina'],['CONTROINDICAZIONE','Lessico'],['SPERIMENTAZIONE','Ricerca'],['DISOCCUPAZIONE','Societa'],['ARCHITETTONICO','Arte'],['GIURISPRUDENZA','Diritto'],['CRISTALLIZZAZIONE','Scienza'],['MICROPROCESSORE','Tecnologia'],['IPERSENSIBILITA','Medicina']]};
function scramble(w){let s;do{s=shuffle([...w]).join('')}while(s===w);return s}
function startAnagram(level){const rounds=shuffle(ANAGRAMS[level]).slice(0,10);let i=0,score=0,hints={easy:3,medium:2,hard:1,extreme:1}[level];app.innerHTML=gameShell('anagram',level,`<div class="progress"><span id="anaProg" style="width:0%"></span></div><div id="anaBox"></div><div id="anaMsg"></div>`);startTimer();render();function render(){if(i>=rounds.length){endRecord('anagram',level,score,true);document.getElementById('anaBox').innerHTML=`<div class="message ok">Partita conclusa. Punteggio: <b>${score}</b>/1000.</div>`;return}const [word,cat]=rounds[i],showCat=!['hard','extreme'].includes(level);document.getElementById('anaProg').style.width=`${i/rounds.length*100}%`;document.getElementById('anaBox').innerHTML=`<div class="message">Parola ${i+1}/10${showCat?` · Categoria: <b>${cat}</b>`:''}</div><div class="big-word">${scramble(word)}</div><div class="answer-row"><input id="anaInput" autocomplete="off" placeholder="Scrivi la parola"><button id="anaOk" class="primary">Conferma</button></div><div class="actions"><button id="anaHint" class="secondary">💡 Aiuto (${hints})</button><button id="anaSkip" class="secondary">Salta</button></div>`;const input=document.getElementById('anaInput');input.focus();document.getElementById('anaOk').onclick=check;input.onkeydown=e=>{if(e.key==='Enter')check()};document.getElementById('anaHint').onclick=()=>{if(!hints)return toast('Nessun aiuto rimasto');hints--;toast(level==='easy'?`Inizia con ${word[0]}`:level==='medium'?`Prime lettere: ${word.slice(0,2)}`:`Contiene la sequenza ${word.slice(1,4)}`);document.getElementById('anaHint').textContent=`💡 Aiuto (${hints})`};document.getElementById('anaSkip').onclick=()=>{i++;render()};function check(){if(norm(input.value)===norm(word)){score+=100;toast('Corretto!');i++;render()}else toast('Non ancora')}}}

// ---------- Quiz ----------
const QUIZ={easy:[
['Qual è la capitale della Francia?',['Parigi','Lione','Marsiglia','Nizza'],0,'Parigi è la capitale della Francia.'],['Quanti lati ha un esagono?',['5','6','7','8'],1,'Un esagono ha sei lati.'],['Quale pianeta è noto come Pianeta Rosso?',['Venere','Marte','Giove','Mercurio'],1,'Marte appare rossastro per gli ossidi di ferro presenti sulla superficie.'],['Chi ha dipinto la Gioconda?',['Michelangelo','Raffaello','Leonardo da Vinci','Caravaggio'],2,'La Gioconda è opera di Leonardo da Vinci.'],['In quale continente si trova il Kenya?',['Asia','Africa','Europa','America'],1,'Il Kenya si trova nell’Africa orientale.'],['Quale gas è più abbondante nell’atmosfera terrestre?',['Ossigeno','Azoto','Anidride carbonica','Idrogeno'],1,'L’azoto costituisce circa il 78% dell’atmosfera.'],['Quale mare bagna Venezia?',['Tirreno','Adriatico','Ionio','Ligure'],1,'Venezia si affaccia sull’Adriatico.'],['Quanto fa 12 × 8?',['86','92','96','104'],2,'12 × 8 = 96.'],['Quale animale è un mammifero?',['Squalo','Delfino','Trota','Polpo'],1,'Il delfino è un mammifero marino.'],['Quale strumento misura la temperatura?',['Barometro','Termometro','Altimetro','Igrometro'],1,'Il termometro misura la temperatura.']],
medium:[
['Quale elemento chimico ha simbolo Fe?',['Fluoro','Ferro','Fermio','Francio'],1,'Fe deriva dal latino ferrum.'],['Quale città è attraversata dal fiume Tamigi?',['Madrid','Londra','Vienna','Praga'],1,'Il Tamigi attraversa Londra.'],['Chi scrisse “Il nome della rosa”?',['Italo Calvino','Umberto Eco','Primo Levi','Dino Buzzati'],1,'Il romanzo fu scritto da Umberto Eco.'],['Qual è il più grande oceano della Terra?',['Atlantico','Indiano','Pacifico','Artico'],2,'Il Pacifico è il più esteso degli oceani.'],['In musica, quante note ha la scala diatonica prima della ripetizione dell’ottava?',['5','6','7','8'],2,'Le note distinte sono sette.'],['Quale organo produce l’insulina?',['Fegato','Pancreas','Rene','Milza'],1,'L’insulina è prodotta dalle cellule beta del pancreas.'],['Quale civiltà costruì Machu Picchu?',['Maya','Aztechi','Inca','Olmechi'],2,'Machu Picchu fu costruita dagli Inca.'],['Qual è la radice quadrata di 144?',['10','11','12','14'],2,'12 × 12 = 144.'],['Quale pittore è associato alla “Notte stellata”?',['Van Gogh','Monet','Picasso','Klimt'],0,'La “Notte stellata” è di Vincent van Gogh.'],['Il Danubio sfocia in quale mare?',['Baltico','Nero','Egeo','Caspio'],1,'Il Danubio sfocia nel Mar Nero.']],
hard:[
['Quale scala misura la durezza dei minerali?',['Richter','Mohs','Beaufort','Mercalli'],1,'La scala di Mohs ordina i minerali per durezza relativa.'],['Chi formulò le leggi del moto planetario?',['Keplero','Galileo','Hubble','Faraday'],0,'Johannes Kepler formulò tre leggi del moto planetario.'],['Qual è la capitale della Slovenia?',['Bratislava','Lubiana','Zagabria','Sarajevo'],1,'Lubiana è la capitale della Slovenia.'],['In quale secolo iniziò la Guerra dei Trent’anni?',['XV','XVI','XVII','XVIII'],2,'La Guerra dei Trent’anni iniziò nel 1618.'],['Quale numero romano rappresenta 49?',['IL','XLIX','XXXXIX','LXI'],1,'49 si scrive XLIX.'],['Quale parte del cervello è particolarmente coinvolta nella coordinazione dei movimenti?',['Cervelletto','Talamo','Ipofisi','Bulbo olfattivo'],0,'Il cervelletto ha un ruolo centrale nella coordinazione motoria.'],['Chi compose “Le quattro stagioni”?',['Bach','Mozart','Vivaldi','Handel'],2,'“Le quattro stagioni” sono concerti di Antonio Vivaldi.'],['Quale stretto separa Asia e Nord America?',['Gibilterra','Bering','Bosforo','Malacca'],1,'Lo stretto di Bering separa Russia e Alaska.'],['Quale unità SI misura la resistenza elettrica?',['Volt','Watt','Ohm','Tesla'],2,'La resistenza elettrica si misura in ohm.'],['Quale romanzo ha come protagonista Raskolnikov?',['Guerra e pace','Delitto e castigo','I demoni','Padri e figli'],1,'Raskolnikov è il protagonista di “Delitto e castigo”.']],
extreme:[
['Quale matematico introdusse formalmente il concetto di algoritmo nel contesto della calcolabilità con una macchina astratta oggi a lui intitolata?',['Alan Turing','David Hilbert','John von Neumann','Kurt Gödel'],0,'La macchina di Turing è centrale nella teoria della calcolabilità.'],['In immunologia, quale classe di anticorpi è tipicamente la principale responsabile delle reazioni allergiche immediate?',['IgA','IgE','IgM','IgD'],1,'Le IgE si legano a mastociti e basofili nelle reazioni di ipersensibilità immediata.'],['Quale trattato del 1648 è considerato convenzionalmente fondativo del moderno sistema degli Stati sovrani europei?',['Utrecht','Vienna','Vestfalia','Tordesillas'],2,'La Pace di Vestfalia del 1648 è il riferimento classico.'],['Quale tra questi filosofi è associato al concetto di “velo d’ignoranza”?',['Rawls','Nozick','Habermas','Popper'],0,'Il velo d’ignoranza è un’idea chiave di John Rawls.'],['Quale struttura cellulare è il principale sito della beta-ossidazione degli acidi grassi?',['Lisosoma','Ribosoma','Mitocondrio','Apparato di Golgi'],2,'La beta-ossidazione avviene prevalentemente nei mitocondri.'],['In linguistica storica, quale fenomeno descrive il passaggio regolare di consonanti germaniche rispetto all’indoeuropeo secondo una legge fonetica?',['Legge di Grimm','Legge di Zipf','Legge di Verner','Legge di Saussure'],0,'La Legge di Grimm descrive il mutamento consonantico germanico, poi affinato da Verner.'],['Quale autore scrisse “La vita: istruzioni per l’uso”?',['Georges Perec','Italo Calvino','Julio Cortázar','Milan Kundera'],0,'Il romanzo è di Georges Perec.'],['Quale grandezza fisica ha dimensioni di energia divisa per tempo?',['Impulso','Potenza','Pressione','Capacità termica'],1,'L’energia per unità di tempo è la potenza.'],['Quale dinastia regnava in Russia al tempo della rivoluzione del 1917?',['Romanov','Rjurik','Hohenzollern','Asburgo'],0,'L’ultima dinastia imperiale russa fu quella dei Romanov.'],['In statistica, quale indice sintetizza la correlazione lineare fra due variabili quantitative?',['Indice di Gini','Coefficiente di Pearson','Indice di Shannon','Test di Levene'],1,'Il coefficiente di Pearson misura la correlazione lineare.']]};
function startQuiz(level){const qs=shuffle(QUIZ[level]).slice(0,10);let i=0,score=0;app.innerHTML=gameShell('quiz',level,`<div class="progress"><span id="quizProg"></span></div><div id="quizBox"></div>`);startTimer();render();function render(){if(i>=qs.length){endRecord('quiz',level,score,true);document.getElementById('quizBox').innerHTML=`<div class="message ok">Quiz concluso: <b>${score}/1000</b>.</div>`;return}document.getElementById('quizProg').style.width=`${i/qs.length*100}%`;const [q,choices]=qs[i];document.getElementById('quizBox').innerHTML=`<div class="message">Domanda ${i+1}/10</div><div class="quiz-q">${q}</div><div class="choices">${choices.map((c,j)=>`<button class="choice" data-j="${j}">${c}</button>`).join('')}</div><div id="quizExplain"></div>`;document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>answer(+b.dataset.j))}function answer(j){const [q,choices,correct,explain]=qs[i];document.querySelectorAll('.choice').forEach((b,k)=>{b.disabled=true;if(k===correct)b.classList.add('correct');if(k===j&&j!==correct)b.classList.add('wrong')});if(j===correct)score+=100;document.getElementById('quizExplain').innerHTML=`<div class="message ${j===correct?'ok':'bad'}">${j===correct?'Corretto.':'Risposta errata.'} ${explain}</div><div class="actions"><button id="nextQuiz" class="primary">Avanti</button></div>`;document.getElementById('nextQuiz').onclick=()=>{i++;render()}}}

// ---------- Logica ----------
const LOGIC={easy:[
['Completa: 2, 4, 6, 8, …',['9','10','11','12'],1,'Si aggiunge 2.'],['Marco è più alto di Paolo; Paolo è più alto di Anna. Chi è il più basso?',['Marco','Paolo','Anna','Non si sa'],2,'Anna è più bassa di Paolo, che è più basso di Marco.'],['Quale elemento è diverso?',['Quadrato','Triangolo','Cerchio','Rettangolo'],2,'Il cerchio non è un poligono.'],['Se A=1, B=2, C=3, quanto vale CAB?',['312','321','213','123'],0,'C=3, A=1, B=2.'],['Completa: 5, 10, 15, 20, …',['22','24','25','30'],2,'Si aggiunge 5.'],['Tutti i gatti sono mammiferi. Micio è un gatto. Micio è…',['Un rettile','Un mammifero','Un uccello','Non si può dire'],1,'È una deduzione diretta.'],['Completa: A, C, E, G, …',['H','I','J','K'],1,'Si salta una lettera ogni volta.'],['Se oggi è lunedì, che giorno sarà tra 3 giorni?',['Martedì','Mercoledì','Giovedì','Venerdì'],2,'Lunedì + 3 giorni = giovedì.']],
medium:[
['Completa: 3, 6, 12, 24, …',['36','42','48','60'],2,'Ogni termine raddoppia.'],['Anna è davanti a Bruno ma dietro Carlo. Chi è primo tra i tre?',['Anna','Bruno','Carlo','Pari'],2,'L’ordine è Carlo, Anna, Bruno.'],['Completa: 1, 4, 9, 16, …',['20','24','25','32'],2,'Sono i quadrati 1², 2², 3², 4², 5².'],['Se CASA diventa DBTB spostando ogni lettera di +1, come diventa LUNA?',['MVOB','MVOA','LUMB','NVPB'],0,'L→M, U→V, N→O, A→B.'],['Tre scatole: rossa, blu, verde. La rossa non è prima, la verde è dopo la blu. Quale può essere l’ordine?',['R-V-B','B-R-V','V-B-R','R-B-V'],1,'B-R-V rispetta entrambe le condizioni.'],['Completa: 2, 3, 5, 8, 12, …',['15','16','17','18'],2,'Gli incrementi sono +1,+2,+3,+4,+5.'],['Se 5 macchine producono 5 pezzi in 5 minuti, quante macchine servono per produrre 100 pezzi in 5 minuti?',['20','50','100','500'],2,'Ogni macchina produce un pezzo in 5 minuti.'],['Quale coppia continua: AB, DE, GH, …',['IJ','JK','KL','MN'],1,'Le coppie iniziano ogni tre lettere: A, D, G, J.']],
hard:[
['Completa: 1, 2, 6, 24, 120, …',['240','360','600','720'],3,'È la sequenza dei fattoriali: 1!,2!,3!,4!,5!,6!.'],['A dice: “B mente”. B dice: “C mente”. C dice: “A e B mentono”. Se una sola frase è vera, chi dice la verità?',['A','B','C','Nessuno'],1,'Con B vero: C mente e la frase di C è falsa; A mente dicendo che B mente.'],['Un orologio segna le 3:15. Qual è l’angolo minore tra le lancette?',['0°','7,5°','15°','30°'],1,'La lancetta delle ore avanza 0,5° al minuto: a 3:15 è a 97,5°, quella dei minuti a 90°.'],['Completa: 2, 5, 11, 23, 47, …',['71','94','95','96'],2,'Ogni termine è il precedente ×2 +1.'],['Cinque persone si stringono la mano una sola volta con ciascun’altra. Quante strette di mano?',['5','10','15','20'],1,'Le coppie sono 5×4/2 = 10.'],['Se alcuni A sono B e nessun B è C, quale affermazione è certamente vera?',['Nessun A è C','Alcuni A non sono C','Tutti gli A sono B','Alcuni C sono A'],1,'Gli A che sono B non possono essere C; quindi almeno alcuni A non sono C.'],['In un codice, 2→6, 3→12, 4→20. Quanto vale 7?',['42','49','54','56'],3,'La regola è n×(n+1).'],['Una famiglia ha due genitori e tre figli. Ogni figlio ha una sorella. Qual è il numero minimo di persone?',['4','5','6','7'],1,'I tre figli possono includere la stessa sorella: in totale 5 persone.']],
extreme:[
['Quattro amici siedono in fila. Luca non è né primo né ultimo. Marta siede immediatamente a sinistra di Paolo. Gianni non è accanto a Paolo. Chi occupa il secondo posto?',['Luca','Marta','Paolo','Gianni'],1,'Le uniche disposizioni coerenti portano alla coppia Marta-Paolo nelle posizioni 2-3.'],
['Un codice a 4 cifre usa le cifre 1,2,3,4 senza ripetizioni. Il 1 non può stare in prima posizione, il 4 deve stare dopo il 2 e il 3 non può stare in ultima posizione. Quanti codici possibili esistono?',['2','3','4','5'],2,'I codici validi sono 2314, 2341, 2134 e 3124: in totale 4.'],
['Cinque case colorate sono in fila. La rossa è a sinistra della blu ma non adiacente. La verde è esattamente in mezzo. La gialla è a destra della blu. Quale colore può trovarsi nella prima casa?',['Blu','Gialla','Rossa','Verde'],2,'Con la verde fissa al centro, la rossa può occupare la prima casa per soddisfare tutti i vincoli.'],
['Una cassaforte richiede il numero successivo della serie: 4, 9, 19, 39, 79, ?',['119','139','159','169'],2,'Ogni termine è il precedente ×2 +1, tranne il primo passaggio che porta da 4 a 9. 79×2+1=159.'],
['Tre interruttori A, B e C controllano una lampada. Se A è acceso, B deve essere spento. Se C è spento, almeno uno tra A e B deve essere acceso. Quale configurazione è impossibile?',['A acceso, B acceso, C acceso','A spento, B acceso, C spento','A spento, B spento, C acceso','A acceso, B spento, C spento'],0,'Se A è acceso, B deve essere spento: quindi A acceso e B acceso è impossibile.'],
['In una gara, Anna arriva prima di Bruno, Bruno prima di Carla, ma Davide arriva prima di Anna. Chi è certamente terzo?',['Anna','Bruno','Carla','Davide'],1,'L’ordine relativo è Davide, Anna, Bruno, Carla; Bruno è terzo.'],
['Se la parola ENIGMA viene codificata sostituendo ogni lettera con la successiva nell’alfabeto italiano base (A→B, B→C, …, Z→A), come si codifica?',['FOJHNB','FNJHNB','FOJHMA','FOKHNB'],0,'E→F, N→O, I→J, G→H, M→N, A→B.'],
['Un quadrato di lato 10 contiene un cerchio inscritto. Qual è l’area esterna al cerchio ma interna al quadrato?',['100−25π','100−50π','50−25π','100−10π'],0,'Area quadrato 100, area cerchio πr² con r=5, quindi 25π.'] ]};
function startLogic(level){const qs=shuffle(LOGIC[level]);let i=0,score=0;app.innerHTML=gameShell('logic',level,`<div class="progress"><span id="logicProg"></span></div><div id="logicBox"></div>`);startTimer();render();function render(){if(i>=qs.length){endRecord('logic',level,score,true);document.getElementById('logicBox').innerHTML=`<div class="message ok">Sessione completata. Punteggio: <b>${score}/${qs.length*100}</b>.</div>`;return}document.getElementById('logicProg').style.width=`${i/qs.length*100}%`;const [q,c]=qs[i];document.getElementById('logicBox').innerHTML=`<div class="logic-panel"><div class="logic-title"><h3>🧠 Enigma ${i+1}/${qs.length}</h3><span class="badge">${LEVEL_NAMES[level]}</span></div><div class="logic-meta"><span class="logic-chip">Tempo attivo</span><span class="logic-chip">Punteggio ${score}</span><span class="logic-chip">${level==='extreme'?'Più vincoli, più passaggi':'Una sola soluzione corretta'}</span></div><div class="quiz-q">${q}</div><div class="choices">${c.map((x,j)=>`<button class="choice" data-j="${j}">${x}</button>`).join('')}</div><div id="logicExplain"></div></div>`;document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>ans(+b.dataset.j))}function ans(j){const [q,c,ok,why]=qs[i];document.querySelectorAll('.choice').forEach((b,k)=>{b.disabled=true;if(k===ok)b.classList.add('correct');if(k===j&&j!==ok)b.classList.add('wrong')});if(j===ok)score+=100;document.getElementById('logicExplain').innerHTML=`<div class="message ${j===ok?'ok':'bad'}">${j===ok?'Corretto.':'Non è la soluzione.'} ${why}</div><div class="actions"><button id="logicNext" class="primary">Avanti</button></div>`;document.getElementById('logicNext').onclick=()=>{i++;render()}}}

// ---------- Escape Room ----------
const ESCAPES={easy:{title:'La stanza dell’orologio',intro:'Sei in una biblioteca chiusa. Sulla porta c’è una tastiera numerica. Per uscire devi ricavare quattro risposte.',items:['🗝️ Chiave','📝 Appunto'],spots:['Porta','Scaffale','Scrivania'],steps:[
['Sul tavolo trovi: 2, 4, 6, 8, ?. Inserisci il numero mancante.','10','La sequenza aumenta di 2.'],['Un foglio dice: “La terza lettera di CASA”. Qual è?','S','Conta C=1, A=2, S=3.'],['Un orologio è fermo sulle 7. Il biglietto dice “raddoppia l’ora”.','14','7 × 2.'],['La tastiera chiede la somma di 1+4.','5','È una semplice somma.']]},
medium:{title:'Il laboratorio spento',intro:'Un blackout ha bloccato il laboratorio. Devi riattivare il sistema risolvendo sei controlli in sequenza.',items:['🔑 Chiave inglese','💳 Tessera','🧪 Fiala'],spots:['Monitor','Cassaforte','Porta','Scrivania'],steps:[
['Completa il codice: 3, 6, 12, 24, ?','48','Ogni numero raddoppia.'],['Se A=1, B=2, C=3, quanto vale BAD come sequenza di cifre?','214','B=2, A=1, D=4.'],['Una nota dice: “Il contrario di ROMA”. Scrivilo.','AMOR','Leggi la parola al contrario.'],['Tre interruttori sono numerati 2, 3 e 5. Inserisci il loro prodotto.','30','Moltiplica 2×3×5.'],['Codice Cesare +1: DBTB corrisponde a quale parola italiana?','CASA','Sposta ogni lettera indietro di una posizione.'],['Ultimo controllo: radice quadrata di 81.','9','9×9=81.']]},
hard:{title:'Il vagone sigillato',intro:'Il treno è fermo in galleria. Il vagone di controllo è sigillato e richiede otto chiavi logiche.',items:['🗝️ Chiave','🧾 Biglietto','🪫 Batteria'],spots:['Portello','Pannello','Valigetta','Sedile'],steps:[
['Sequenza: 2, 5, 11, 23, 47, ?','95','Ogni termine è il precedente ×2 +1.'],['Scrivi in cifre romane il numero 14.','XIV','10 + 4 = X + IV.'],['Se ogni lettera avanza di 2, CASA diventa ECUC. Decodifica NWPC tornando indietro di 2.','LUNA','N→L, W→U, P→N, C→A.'],['Un quadrato ha perimetro 36. Quanto misura il lato?','9','36÷4.'],['Qual è il numero successivo: 1, 2, 6, 24, 120, ?','720','Sono fattoriali.'],['Scrivi al contrario la parola ENIGMA.','AMGINE','Inverti l’ordine delle lettere.'],['Quante diagonali ha un quadrato?','2','Un quadrato ha due diagonali.'],['Ultima chiave: 7×8−6.','50','56−6.']]},
extreme:{title:'Il laboratorio segreto',intro:'L’allarme è attivo, la porta blindata è bloccata e il sistema si resetta a ogni errore. Devi combinare indizi, codici e deduzioni per uscire.',items:['🗝️ Chiave','💳 Tessera','📝 Appunto','🧪 Fiala'],spots:['Monitor','Cassaforte','Porta','Scrivania'],steps:[
['Dalla console ottieni la serie 4, 9, 19, 39, 79, ?. Qual è il valore successivo?','159','Ogni numero raddoppia e si aggiunge 1.'],['Su un badge c’è scritto: “Prendi la parola LUNA e sposta ogni lettera avanti di 1”. Che parola ottieni?','MVOB','L→M, U→V, N→O, A→B.'],['Un monitor mostra il numero romano XXIV. Converti in cifra araba.','24','XXIV = 20 + 4.'],['In una teca leggi: “Il codice è la differenza tra 144 e 89”.','55','144 − 89 = 55.'],['Una cassaforte richiede la terza lettera della parola CRITTOGRAFIA.','I','C=1, R=2, I=3.'],['Un messaggio dice: “Se la chiave è 7, calcola 7×7−8”.','41','49 − 8 = 41.'],['Sul pannello trovi: 2, 3, 5, 8, 12, ?. Inserisci il successivo.','17','Gli incrementi sono +1,+2,+3,+4,+5.'],['Una luce rossa lampeggia con la scritta “RADQ81”. Interpreta il testo e inserisci il valore.','9','Radice quadrata di 81.'],['L’ultima serratura richiede il contrario di AMOR.','ROMA','Inverti la parola.'],['Codice finale: somma i valori 24 e 41 e sottrai 9.','56','24 + 41 − 9 = 56.']]}};
function startEscape(level){const e=ESCAPES[level];let i=0,score=0,hints={easy:3,medium:2,hard:1,extreme:1}[level];app.innerHTML=gameShell('escape',level,`<div class="progress"><span id="escProg"></span></div><div class="escape-scene-wrap"><div class="escape-stage level-${level}"><div class="escape-title"><h2>${e.title}</h2><p>${e.intro}</p></div><div class="escape-console"></div><div class="escape-safe"></div><div class="escape-desk"></div><div class="escape-door"></div><div class="escape-hotspots">${(e.spots||[]).map((s,idx)=>`<div class="hotspot" style="${['left:8%;top:42%;','left:44%;top:36%;','right:7%;top:50%;','left:20%;bottom:16%;'][idx]||''}">${s}</div>`).join('')}</div><div class="escape-particles"><span></span><span></span><span></span><span></span><span></span></div></div><div class="escape-inventory">${(e.items||[]).map(x=>{const parts=x.split(' ');return `<div class="item-pill"><span>${parts.shift()}</span>${parts.join(' ')}</div>`}).join('')}<div class="item-pill"><span>💡</span>Indizi ${hints}</div></div></div><div id="escBox"></div>`);startTimer();render();function render(){if(i>=e.steps.length){endRecord('escape',level,score,true);document.getElementById('escBox').innerHTML=`<div class="message ok">🔓 Uscita sbloccata. Punteggio: <b>${score}</b>.</div>`;return}document.getElementById('escProg').style.width=`${i/e.steps.length*100}%`;const [q]=e.steps[i];document.getElementById('escBox').innerHTML=`<div class="escape-question"><h3>Enigma ${i+1}/${e.steps.length}</h3><p>${q}</p></div><div class="answer-row" style="margin-top:12px"><input id="escInput" autocomplete="off" placeholder="Inserisci codice o parola"><button id="escOk" class="primary">Prova</button></div><div class="actions"><button id="escHint" class="secondary">💡 Indizio (${hints})</button></div><div id="escMsg"></div>`;document.getElementById('escOk').onclick=check;document.getElementById('escInput').onkeydown=x=>{if(x.key==='Enter')check()};document.getElementById('escHint').onclick=()=>{if(!hints)return toast('Nessun indizio rimasto');hints--;score=Math.max(0,score-20);document.getElementById('escHint').textContent=`💡 Indizio (${hints})`;document.getElementById('escMsg').innerHTML=`<div class="message">${e.steps[i][2]}</div>`;const inv=document.querySelector('.escape-inventory .item-pill:last-child');if(inv)inv.innerHTML=`<span>💡</span>Indizi ${hints}`};document.getElementById('escInput').focus()}function check(){const ans=e.steps[i][1],v=document.getElementById('escInput').value;if(norm(v)===norm(ans)){score+=100;i++;render()}else{score=Math.max(0,score-10);toast('Il codice non è corretto')}}}

// ---------- Partita mista ----------
function startMixed(level){const aq=shuffle(ANAGRAMS[level]).slice(0,2),qq=shuffle(QUIZ[level]).slice(0,2),lq=shuffle(LOGIC[level]).slice(0,2);const tasks=shuffle([
...aq.map(x=>({type:'text',title:'🔡 Anagramma',q:`Ricomponi: ${scramble(x[0])}${['hard','extreme'].includes(level)?'':` · ${x[1]}`}`,answer:x[0],why:`Soluzione: ${x[0]}`})),
...qq.map(x=>({type:'choice',title:'❓ Quiz',q:x[0],choices:x[1],correct:x[2],why:x[3]})),
...lq.map(x=>({type:'choice',title:'🧠 Logica',q:x[0],choices:x[1],correct:x[2],why:x[3]}))]).slice(0,6);let i=0,score=0;app.innerHTML=gameShell('mixed',level,`<div class="progress"><span id="mixProg"></span></div><div id="mixBox"></div>`);startTimer();render();function render(){if(i>=tasks.length){endRecord('mixed',level,score,true);document.getElementById('mixBox').innerHTML=`<div class="message ok">Partita mista completata. Punteggio: <b>${score}/600</b>.</div>`;return}const t=tasks[i];document.getElementById('mixProg').style.width=`${i/tasks.length*100}%`;if(t.type==='text')document.getElementById('mixBox').innerHTML=`<div class="message">Prova ${i+1}/6 · ${t.title}</div><div class="quiz-q">${t.q}</div><div class="answer-row"><input id="mixInput"><button id="mixOk" class="primary">Conferma</button></div>`;else document.getElementById('mixBox').innerHTML=`<div class="message">Prova ${i+1}/6 · ${t.title}</div><div class="quiz-q">${t.q}</div><div class="choices">${t.choices.map((c,j)=>`<button class="choice" data-j="${j}">${c}</button>`).join('')}</div><div id="mixWhy"></div>`;if(t.type==='text'){document.getElementById('mixOk').onclick=()=>{if(norm(document.getElementById('mixInput').value)===norm(t.answer)){score+=100;i++;render()}else toast('Non è corretto')};document.getElementById('mixInput').focus()}else document.querySelectorAll('.choice').forEach(b=>b.onclick=()=>{const j=+b.dataset.j;document.querySelectorAll('.choice').forEach((x,k)=>{x.disabled=true;if(k===t.correct)x.classList.add('correct');if(k===j&&j!==t.correct)x.classList.add('wrong')});if(j===t.correct)score+=100;document.getElementById('mixWhy').innerHTML=`<div class="message ${j===t.correct?'ok':'bad'}">${t.why}</div><div class="actions"><button id="mixNext" class="primary">Avanti</button></div>`;document.getElementById('mixNext').onclick=()=>{i++;render()}})} }

// ---------- Sfida del giorno ----------
function dateSeed(){const d=new Date(),s=Number(`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,'0')}${String(d.getDate()).padStart(2,'0')}`);return s}
function seeded(seed){let x=seed%2147483647;if(x<=0)x+=2147483646;return()=>((x=x*16807%2147483647)-1)/2147483646}
function renderDaily(){const r=seeded(dateSeed()),games=['anagram','quiz','logic','mixed','wordsearch','escape'],game=games[Math.floor(r()*games.length)],levels=['easy','medium','hard','extreme'],level=levels[Math.floor(r()*levels.length)];setHeader('Sfida del giorno',`${LEVEL_NAMES[level]} · cambia ogni giorno`);app.innerHTML=`<section class="hero"><h2>⭐ ${GAME_NAMES[game]}</h2><p>La sfida di oggi è <b>${LEVEL_NAMES[level]}</b>. Sullo stesso dispositivo resta uguale per tutta la giornata.</p><div class="actions"><button class="primary" id="dailyStart">Inizia la sfida</button><button class="secondary" onclick="renderHome()">Torna alla Home</button></div></section>`;document.getElementById('dailyStart').onclick=()=>startGame(game,level)}

// ---------- Archivio locale ----------
function renderArchive(){stopTimer();setHeader('Archivio locale','Storico e backup sul dispositivo');const rows=store.history.slice(0,100);app.innerHTML=`
<div class="stat-grid"><div class="stat"><b>${store.history.length}</b><span>Partite salvate</span></div><div class="stat"><b>${store.history.filter(x=>x.success).length}</b><span>Completate</span></div><div class="stat"><b>${Object.keys(store.stats).length}</b><span>Gioco/livello usati</span></div><div class="stat"><b>${store.history.reduce((m,x)=>Math.max(m,x.score||0),0)}</b><span>Record punti</span></div></div>
<div class="section-title"><h3>Backup</h3></div><div class="actions"><button id="exportBtn" class="primary">Esporta JSON</button><label class="secondary" style="text-align:center">Importa JSON<input id="importFile" type="file" accept="application/json" hidden></label><button id="clearBtn" class="secondary danger">Cancella archivio</button></div>
<div class="section-title"><h3>Ultime partite</h3><small>massimo 100 mostrate</small></div>
${rows.length?`<div style="overflow:auto"><table class="table"><thead><tr><th>Data</th><th>Gioco</th><th>Livello</th><th>Esito</th><th>Punti</th><th>Tempo</th></tr></thead><tbody>${rows.map(x=>`<tr><td>${new Date(x.date).toLocaleString('it-IT',{day:'2-digit',month:'2-digit',year:'2-digit',hour:'2-digit',minute:'2-digit'})}</td><td>${GAME_NAMES[x.game]||x.game}</td><td>${LEVEL_NAMES[x.level]||x.level}</td><td>${x.success?'✅':'—'}</td><td>${x.score}</td><td>${fmtTime(x.seconds||0)}</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">Non ci sono ancora partite archiviate.</div>'}
<p class="footer-note">L'esportazione crea una copia del solo archivio giochi. L'importazione sostituisce l'archivio presente su questo dispositivo.</p>`;
document.getElementById('exportBtn').onclick=()=>{const blob=new Blob([JSON.stringify(store,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=`sala-giochi-backup-${new Date().toISOString().slice(0,10)}.json`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)};document.getElementById('importFile').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{const obj=JSON.parse(await f.text());if(!obj||!Array.isArray(obj.history)||typeof obj.stats!=='object')throw new Error();store=obj;persist();toast('Backup importato');renderArchive()}catch{toast('File di backup non valido')}};document.getElementById('clearBtn').onclick=()=>{if(confirm('Cancellare definitivamente tutto lo storico locale?')){store=freshStore();persist();renderArchive()}}}

if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js').catch(()=>{}));
renderHome();
